# Dependencies
markdown:         redcarpet
pygments:         true
highlighter:      pygments

# Setup
title:            Hyde
tagline:          'A Jekyll theme'

paginate:         5
# Custom vars
version:          2.1.0
