# # Jekyll configuration

name: Yongkook Won (PhD)
# description: A jekyll theme

theme: minima

# highlighter: rouge
# markdown: kramdown
# gems: ['jekyll-paginate']

# exclude: ['README.md', 'LICENSE']
